local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Akon Hub", "DarkTheme")
local Tab = Window:NewTab("Mine")
local Section = Tab:NewSection("Farme")
Section:NewLabel("Auto lave")
Section:NewLabel("Auto kill")
Section:NewLabel("Aurora kill")
Section:NewLabel("Auto monny")
Section:NewLabel("Auto bypass")
Section:NewLabel("Auto kaiton")
Section:NewLabel("coom soon")
local Tab = Window:NewTab("Soon")
local Section = Tab:NewSection("soon")
Section:NewLabel("1")
Section:NewLabel("2")
Section:NewLabel("3")
Section:NewLabel("4")
Section:NewLabel("5")
Section:NewLabel("6")
Section:NewLabel("7")
local Tab = Window:NewTab("soon .1")
local Section = Tab:NewSection("soon")
Section:NewLabel("LabelText")
Section:NewLabel("LabelText")
Section:NewLabel("LabelText")
Section:NewLabel("LabelText")
Section:NewLabel("LabelText")
Section:NewLabel("LabelText")
Section:NewLabel("LabelText")
Section:NewLabel("LabelText")
Section:NewLabel("LabelText")
Section:NewLabel("LabelText")
Section:NewLabel("LabelText")
Section:NewLabel("LabelText")
Section:NewLabel("LabelText")